apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users
spec:
  selector:
    app: users
  ports:
  - port: 80
    targetPort: 8060
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "users-config-maps"
  namespace: default
  labels: 
    app: users
data:
  MYSQL_URL: "mysql-service"
  MYSQL_PORT: "3306"
  DB_NAME: "bestbuydb"
  MYSQL_USER_NAME: "root"
  MYSQL_USER_PASSWORD: "workshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: nimit07/nagp-micro-assign-user:latest
        ports:
        - containerPort: 8060
        env:
          - name: JAEGER_QUERY_API_URL
            valueFrom:
                configMapKeyRef:
                  name: jaeger-config-maps
                  key: JAEGER_QUERY_API_URL
          - name: JAEGER_COLLECTOR_API_URL
            valueFrom:
                configMapKeyRef:
                  key: JAEGER_COLLECTOR_API_URL
                  name: jaeger-config-maps
          - name: MYSQL_URL
            valueFrom:
                configMapKeyRef:
                  key: MYSQL_URL
                  name: users-config-maps
          - name: MYSQL_PORT
            valueFrom:
                configMapKeyRef:
                  key: MYSQL_PORT
                  name: users-config-maps
          - name: DB_NAME
            valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: users-config-maps
          - name: MYSQL_USER_NAME
            valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER_NAME
                  name: users-config-maps
          - name: MYSQL_USER_PASSWORD
            valueFrom:
                secretKeyRef:
                  key: password
                  name: my-db-secret
